### ISSUE TITLE
Revisar traduções do Devise

### ISSUE THREAD

**Issue by pedroCervi** [MakersNetwork/agenda-saude#207]
A mensagem do Devise tá sendo exibida ao tentar logar quando já tem um paciente logado.

Passos para simular o erro:

- Logar com algum __Paciente__
- Voltar na setinha do navegador
- Logar novamente

As views de Devise são as únicas que utilizam i18n, mas definimos apenas algumas traduções presentes no fluxo mais comum. Precisamos revisar se há mais traduções faltando.

![image](https://user-images.githubusercontent.com/21227797/112544336-a1418000-8d95-11eb-802c-a15f28fca1ba.png)

**Comment by jmonteiro** [comment]
Resolvido 🕺
