### ISSUE TITLE
Fazer carregamento inicial de bairros no ambiente local

### ISSUE THREAD

**Issue by pedroCervi** [MakersNetwork/agenda-saude#208]
Hoje o script `populate.rb` é capaz de popular os bairros, mas não há nada automatizado para executá-lo local. Podemos adicionar isso na seed de alguma forma.

**Comment by jmonteiro** [comment]
Encerrando já que optamos por manter o sistema neutro (não específico a Joinville) e criamos interface admin para bairros.
