### ISSUE TITLE
Revisar layout

### ISSUE THREAD

**Issue by pedroCervi** [MakersNetwork/agenda-saude#219]
- [ ] Diminuir width do botão "alterar meus dados" em https://vacinajoinville.com.br/time_slot
- [ ] Diminuir o width do botão "voltar" em https://vacinajoinville.com.br/time_slot?start_time=2021-01-21+08%3A15%3A00+-0300&ubs_id=67

**Comment by jmonteiro** [comment]
Não mais relevante com o refactor.
