### ISSUE TITLE
Alguns usuários não conseguem editar seus dados

### ISSUE THREAD

**Issue by pedroCervi** [MakersNetwork/agenda-saude#242]
#### Essa issue é de um card antigo (não sabemos se está ocorrendo)

Temos 2 ocorrências de um [erro](https://sentry.io/organizations/magrathealabs/issues/2033688569/?project=5191494&query=is%3Aunresolved) que estouraram para o mesmo usuário. É possível que ele esteja com a data de nascimento incorreta no banco (devido ao [problema de datas](https://github.com/MakersNetwork/agenda-saude/issues/52) já consertado) que causa algum erro ao renderizar a nova seleção de datas.

Precisamos prever esse erro ou arrumar retroativamente as datas que ficaram erradas no banco.

**Comment by jmonteiro** [comment]
Arrumado.
