### ISSUE TITLE
Data de nascimento não está sendo formatada corretamente

### ISSUE THREAD

**Issue by juuh42dias** [MakersNetwork/agenda-saude#52]
Algumas datas estão sendo salvas em formato DD/MM/YYYY enquanto outras em YYYY-DD-MM

<img width="124" alt="Screen_Shot_2020-04-15_at_14 42 16" src="https://user-images.githubusercontent.com/1828204/81812380-6d9e9400-94fc-11ea-8ba9-7ebad6433228.png">

**Comment by juuh42dias** [comment]
Foi feita uma correção direta no banco mas ainda é necessário investigar se o problema persiste e criar testes garantindo que o erro/bug tenha sido eliminado.

**Comment by Mat-Bit** [comment]
Alguns usuários estão tendo dificuldade em conseguir preencher corretamente a data de nascimento quando aparece o calendário (principalmente usuários que acessam o sistema pelo celular), e acabam errando o ano principalmente.

Uma sugestão é alterar o campo do formulário para o tipo texto com uma máscara e placeholder e fazer alguma validação que seja necessário no `registrations_controller.rb`
