### ISSUE TITLE
Permitir que cada unidade altere os dias "adiante" para agendamentos

### ISSUE THREAD

**Issue by juuh42dias** [MakersNetwork/agenda-saude#57]
Dar a opção para o operador alterar a quantidade de dias para frente que a unidade pode disponibilizar para agendamento (que hoje é fixo de 7 dias);

Extra: Considerar apenas os dias úteis.

**Comment by Mat-Bit** [comment]
Há uma necessidade para que as unidades (Ubs) possam abrir agendamentos para alguns dias específicos da semana (ou até mesmo somente um dia da semana), e podendo abrir ocasionalmente no sábado ou domingo.

Uma ideia é de utilizar um *checkbox* para cada dia da semana que a unidade deseja abrir, que juntamente com o horário que a unidade estará aberta e os dias "adiante" para a unidade disponibilizar o atendimento, será uma opção mais completa e versátil para atender as especificidades de cada unidade.

**Comment by Mat-Bit** [comment]
O mais assertivo para resolver essa issue e atender as demandas das unidades de saúde de forma geral, seria dispor uma data (calendário) para o operador de cada unidade escolher de término dos agendamentos.
Para dar um maior contexto, geralmente campanhas de vacinação possuem uma data para encerrar, o operador fornecendo essa informação, o sistema poderia calcular a diferença do dia limite e o dia atual e este seria o intervalo de dias com agendas disponíveis.
