### ISSUE TITLE
Extrair código repetido nas views em partials

### ISSUE THREAD

**Issue by laurogripa** [MakersNetwork/agenda-saude#64]
Exemplo, o trecho abaixo aparece em diversos lugares:

```
<div class="row text-center mt-5 mb-5">
  <div class="col">
    <small class="text-muted">Para mais informações sobre eventos de saúde da cidade, acesse:<br>
    <a href="https://www.joinville.sc.gov.br/?post_type=evento&tag-tipo-evento=conscientizacao&s=">https://www.joinville.sc.gov.br/evento/conscientizacao/</a></small>
  </div>
</div>
```

Poderia ser extraído para uma partial, assim como alguns alerts.

**Comment by CamargoKmila** [comment]
Vou puxar essa issue

**Comment by CamargoKmila** [comment]
Oi @laurogripa comecei a ver essa issue pelo trecho que você citou na descrição. O que encontrei foram dois arquivos que tem esses trechos parecidos e apenas uma diferença no link e classe de CSS.
A minha duvida é a seguinte: O link desses arquivo realmente devem ser diferentes ou faltou atualizar um dos dois? Abaixo os trechos dos arquivos que encontrei (código encontrado na master. Não consegui subir a master-covid ainda)

app/views/patients/bedridden.html.erb

`<div class="row text-center mt-5 mb-5">
  <div class="col">
    <small class="text-muted">Para mais informações sobre eventos de saúde da cidade, acesse:<br>
    <a href="https://www.joinville.sc.gov.br/?post_type=evento&tag-tipo-evento=conscientizacao&s=">https://www.joinville.sc.gov.br/evento/conscientizacao/</a></small>
  </div>
</div>`

 app/views/patients/not_allowed.html.erb

`<div class="row text-center">
  <div class="col">
    <small class="text-muted">Para mais informações sobre eventos de saúde da cidade, acesse:<br>
    <a href="https://www.joinville.sc.gov.br/coronavirus/">https://www.joinville.sc.gov.br/coronavirus/</a></small>
  </div>
</div>`

**Comment by RafaelaMachado** [comment]
@laurogripa

**Comment by juuh42dias** [comment]
@laurogripa

**Comment by jmonteiro** [comment]
Resolvido 🕺
