### ISSUE TITLE
Alta latência no endpoint TimeSlotController#index

### ISSUE THREAD

**Issue by pedroCervi** [MakersNetwork/agenda-saude#79]
[new relic](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXciLCJlbnRpdHlJZCI6Ik1qZzVOalUwTW54QlVFMThRVkJRVEVsRFFWUkpUMDU4TnpZM09EazFPRGM1In0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNamc1TmpVME1ueEJVRTE4UVZCUVRFbERRVlJKVDA1OE56WTNPRGsxT0RjNSIsInNlbGVjdGVkTmVyZGxldCI6eyJuZXJkbGV0SWQiOiJhcG0tbmVyZGxldHMub3ZlcnZpZXcifX0=&platform[accountId]=2896542&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true)

![Selection_139](https://user-images.githubusercontent.com/21227797/95000863-ee892580-059a-11eb-827f-40fca80b50c8.png)

### Contexto
Hoje temos uma [ação](https://github.com/Makers-Network/agenda-saude/blob/master/app/controllers/time_slot_controller.rb#L51-L56) nesse controller que pega todos os slots de agendamento disponiveis. Provavelmente há alguma forma de simplificar essa requisição e tornar ela mais rápida para o usuário. Hoje o impacto está sendo que muitas vezes o servidor dá um timeout.

A complexidade dessa consulta é que as UBS's tem parâmetros de configuração como tempo da consulta, intervalo entre consultas e horário de funcionamento da UBS. Além disso, tem os próprios agendamentos que concorrem com essa lógica que mostra os agendamentos disponíveis.

Esse problema escalou com o aumento da disponibilidade de testes rápidos em Joinville nas últimas semanas.

### Ideias
Uma alternativa seria montar uma consulta pequena para o usuário e ir alimentando mais opções com o scroll (estilo dale ponto)

**Comment by Mat-Bit** [comment]
Segue abaixo uma imagem enviada por um dos coordenadores do projeto do Teste Rápido pro Covid da Secretaria da Saúde, apontando que diariamente entre 11 e 14h o sistema fica sobrecarregado, **chegando a exceder o tempo para resposta e gerando o erro** (conforme imagem abaixo), devido ao processamento para esse endpoint:

![application_error](https://user-images.githubusercontent.com/19494561/95484202-8bb2d800-0966-11eb-927c-583e381e4ffb.jpeg)

Salientando a importância para apuração e implementação de uma nova forma para apresentar os horários disponíveis.

**Comment by Mat-Bit** [comment]
Uma outra sugestão seria processar todos os horários disponíveis gerados pela unidade quando a mesma é **Ativada** (no ambiente do operador) e persistir esses slots em uma tabela no Banco de Dados.

Toda vez que um usuário reserva um horário, isso reflete nessa tabela por meio de um atributo `reserved` (por exemplo), e toda vez que um usúario acessa o sistema que acessa esse endpoit, o processamento seria simplificado para ler essa tabela e retornar somente os horários que o atributo `reserved` é `false`.

**Comment by pedroCervi** [comment]
![Selection_197](https://user-images.githubusercontent.com/21227797/97790132-c2b28d00-1ba4-11eb-8e2e-487ce5267136.png)

O fix de pegar por dia  baixou as requisições de ~15s para 700ms. Boua! :clap:
