### ISSUE TITLE
Editar o bairro não altera a UBS principal para um paciente

### ISSUE THREAD

**Issue by gabrielamafra** [MakersNetwork/agenda-saude#97]
Adicionamos a tela de edição, mas a chamada `set_main_ubs` que define uma UBS para o paciente não é chamada durante a edição, somente na criação.

Precisamos entender se é ok permitir que os pacientes editem esse campo a fim de "escolher" outras UBS, e cuidar para não fazer chamadas desnecessárias do `set_main_ubs` já que ele escolhe uma UBS aleatória em certas situações.

**Comment by jmonteiro** [comment]
Resolvido 🕺
